COLUMN_NUM = 11
TARGET_URL = (
    "https://docs.google.com/spreadsheets/d/e/2PACX-1vRmmWiBmMMD43m5VtZq"
    "54nKlmj0ZtythsA1qCpegwx-iRptx2HEsG0T3cQlG1r2AIiKxBWnaurJZQ9Q/pubhtml#"
)
DB_NAME = "VCTContractsDB"
TABLE_NAME = "VCTContractsTable"
# 以下のデフォルト値は環境変数で設定するため使われることはない
HOST_NAME = "EXAMPLE_HOST_NAME"
USER_NAME = "EXAMPLE_USER_NAME"
PASSWORD = "EXAMPLE_PASSWORD"
WEBHOOK_URL = "EXAMPLE_WEBHOOK_URL"
WEBHOOK_URL_SIMULATE = "EXAMPLE_WEBHOOK_URL_SIMULATE"
